name: Build & Release Windows App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: electron-build
          path: dist/*.exe

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: electron-build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
